name: Simple CI

on: [pull_request]

jobs:
  run-ci:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'
    - run: npm install
    - name: Check if the git repository is clean
      run: $(exit $(git status --porcelain --untracked-files=no | head -255 | wc -l)) || (echo "Dirty git tree"; git diff; exit 1)
    - run: npm run lint
  clang:
    name: Clang-Format Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        path:
          - 'ios'
          - 'android'
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: jidicula/clang-format-action@654a770daa28443dd111d133e4083e21c1075674 # v4.18.0
      with:
        clang-format-version: '17'
        check-path: ${{ matrix.path }}
        include-regex: '^.*(\.h|\.m|\.java)'