name: iOS CI
on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.md'

jobs:
  ios-compile:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'

    - name: Cache cocoapods
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      with:
        path: ./examples/GumTestApp/ios/Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-

    - name: Install node modules
      run: npm install

    - name: Install example node modules
      working-directory: ./examples/GumTestApp/
      run: npm install

    - name: Pod install
      working-directory: ./examples/GumTestApp/ios
      run: pod install

    - name: Compile iOS Example
      working-directory: ./examples/GumTestApp/ios
      run: |
        set -o pipefail && \
        xcodebuild -workspace GumTestApp.xcworkspace/ \
          -scheme GumTestApp \
          -destination generic/platform=iOS \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGN_ENTITLEMENTS="" \
          CODE_SIGNING_ALLOWED="NO" clean build \
        | xcpretty
